In [1]:
import torch
from torch.utils.data import DataLoader
from torch import nn
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("C:/Users/Ishit/Desktop/train.csv")
final_test=pd.read_csv("C:/Users/Ishit/Desktop/test.csv")
iden=final_test.id.copy()
data=data.loc[:,data.columns != "id"]
final_test=final_test.loc[:,final_test.columns != "id"]
data=data.replace({"Class_1"},0)
data=data.replace({"Class_2"},1)
data=data.replace({"Class_3"},2)
data=data.replace({"Class_4"},3)
data=data.replace({"Class_5"},4)
data=data.replace({"Class_6"},5)
data=data.replace({"Class_7"},6)
data=data.replace({"Class_8"},7)
data=data.replace({"Class_9"},8)

col = [str(i) for i in range(0,75)]
final_test.columns = col
col.append('target')
data.columns = col
col.pop(-1)
data[col] = data[col]/data[col].max()

split=160000
x = data[:split][col]
y = data[:split].target
xt = data[split:][col]
yt = data[split:].target
print(x.shape, xt.shape)
y.head(), yt.head()

(160000, 75) (40000, 75)


(0    5
 1    5
 2    1
 3    7
 4    1
 Name: target, dtype: int64,
 160000    0
 160001    5
 160002    2
 160003    1
 160004    1
 Name: target, dtype: int64)

In [3]:
train_x = torch.tensor(x.values.astype(np.float32))
train_y = torch.tensor(y.values.astype(np.int64))
train_x[0], train_y[0]

(tensor([0.0000, 0.0000, 0.0938, 0.0143, 0.0000, 0.0000, 0.0000, 0.0000, 0.1842,
         0.0000, 0.0000, 0.0000, 0.0811, 0.0000, 0.0312, 0.0000, 0.0000, 0.2143,
         0.1364, 0.0038, 0.0000, 0.0606, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0095, 0.0000, 0.0000, 0.0256, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.3235, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1429, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0536, 0.0000, 0.0263, 0.0833,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0125, 0.0098,
         0.0000, 0.0000, 0.0556, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0328, 0.0000, 0.0000]),
 tensor(5))

In [4]:
test_x = torch.tensor(xt.values.astype(np.float32))
test_y = torch.tensor(yt.values.astype(np.int64))
test_x[0], test_y[0]

(tensor([0.0000, 0.0196, 0.2031, 0.1143, 0.0000, 0.0658, 0.0233, 0.0000, 0.0526,
         0.0000, 0.0303, 0.0000, 0.0000, 0.0000, 0.0312, 0.0000, 0.0000, 0.0000,
         0.3182, 0.0000, 0.0333, 0.0000, 0.0000, 0.1818, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0256, 0.0641, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0294, 0.0000, 0.1224, 0.0000, 0.0274, 0.0000, 0.0159, 0.0741,
         0.0000, 0.0000, 0.0309, 0.0000, 0.1316, 0.0000, 0.0137, 0.0526, 0.0278,
         0.0000, 0.0000, 0.0652, 0.0000, 0.0333, 0.0028, 0.0043, 0.0250, 0.0588,
         0.0000, 0.2800, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0667,
         0.0656, 0.3154, 0.0577]),
 tensor(0))

In [5]:
from torch.utils.data import Dataset
class mydataset(Dataset):
    def __init__(self, data, labels):
        self.labels = labels
        self.data = data
    def __len__(self):
        return len(self.labels)
    def __getitem__(self,idx):
        item = self.data[idx]
        label = self.labels[idx]
        return (item,label)
training_data = mydataset(train_x,train_y)
testing_data = mydataset(test_x,test_y)
training_data, testing_data, next(iter(training_data))

(<__main__.mydataset at 0x22d23d49a60>,
 (tensor([0.0000, 0.0000, 0.0938, 0.0143, 0.0000, 0.0000, 0.0000, 0.0000, 0.1842,
          0.0000, 0.0000, 0.0000, 0.0811, 0.0000, 0.0312, 0.0000, 0.0000, 0.2143,
          0.1364, 0.0038, 0.0000, 0.0606, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0095, 0.0000, 0.0000, 0.0256, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.3235, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1429, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0536, 0.0000, 0.0263, 0.0833,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0125, 0.0098,
          0.0000, 0.0000, 0.0556, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0328, 0.0000, 0.0000]),
  tensor(5)))

In [6]:
batch_size=100
train_dataloader= torch.utils.data.DataLoader(training_data,batch_size=batch_size)
test_dataloader= torch.utils.data.DataLoader(testing_data,batch_size=batch_size)

In [7]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten= nn.Flatten()
        self.linear_relu_stack=nn.Sequential(
            nn.Linear(75,512),
            nn.ReLU(),
            nn.Linear(512,100),
            nn.ReLU(),
            nn.Linear(100,9),
            nn.ReLU()
        )
    
    def forward(self, x):
        x=self.flatten(x)
        logits= self.linear_relu_stack(x)
        return logits

In [8]:
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=75, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=100, bias=True)
    (3): ReLU()
    (4): Linear(in_features=100, out_features=9, bias=True)
    (5): ReLU()
  )
)


In [9]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [10]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X,y) in enumerate(dataloader):
        pred = model(X)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [11]:
def test(dataloader, model):
    size = len(dataloader.dataset)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= size
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [12]:
epochs = 50
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model)
print("Done!")

Epoch 1
-------------------------------
loss: 2.194272  [    0/160000]
loss: 2.146138  [10000/160000]
loss: 2.089509  [20000/160000]
loss: 2.018619  [30000/160000]
loss: 2.068237  [40000/160000]
loss: 1.894754  [50000/160000]
loss: 1.964463  [60000/160000]
loss: 2.018481  [70000/160000]
loss: 1.899026  [80000/160000]
loss: 2.055381  [90000/160000]
loss: 1.900743  [100000/160000]
loss: 1.967668  [110000/160000]
loss: 1.979128  [120000/160000]
loss: 1.880884  [130000/160000]
loss: 1.941927  [140000/160000]
loss: 1.869071  [150000/160000]
Test Error: 
 Accuracy: 25.9%, Avg loss: 0.019197 

Epoch 2
-------------------------------
loss: 1.876452  [    0/160000]
loss: 2.014608  [10000/160000]
loss: 1.940943  [20000/160000]
loss: 1.847537  [30000/160000]
loss: 2.002988  [40000/160000]
loss: 1.792114  [50000/160000]
loss: 1.923121  [60000/160000]
loss: 2.014712  [70000/160000]
loss: 1.838631  [80000/160000]
loss: 2.057376  [90000/160000]
loss: 1.884014  [100000/160000]
loss: 1.953006  [110000/

loss: 1.866179  [140000/160000]
loss: 1.840891  [150000/160000]
Test Error: 
 Accuracy: 34.3%, Avg loss: 0.018274 

Epoch 15
-------------------------------
loss: 1.830817  [    0/160000]
loss: 2.007550  [10000/160000]
loss: 1.749359  [20000/160000]
loss: 1.758910  [30000/160000]
loss: 1.889328  [40000/160000]
loss: 1.761724  [50000/160000]
loss: 1.792510  [60000/160000]
loss: 1.909668  [70000/160000]
loss: 1.724328  [80000/160000]
loss: 1.984398  [90000/160000]
loss: 1.830923  [100000/160000]
loss: 1.821657  [110000/160000]
loss: 1.960086  [120000/160000]
loss: 1.806692  [130000/160000]
loss: 1.863599  [140000/160000]
loss: 1.840713  [150000/160000]
Test Error: 
 Accuracy: 34.3%, Avg loss: 0.018248 

Epoch 16
-------------------------------
loss: 1.831617  [    0/160000]
loss: 2.004587  [10000/160000]
loss: 1.746415  [20000/160000]
loss: 1.758093  [30000/160000]
loss: 1.888692  [40000/160000]
loss: 1.759739  [50000/160000]
loss: 1.787006  [60000/160000]
loss: 1.907452  [70000/160000]


loss: 1.809685  [100000/160000]
loss: 1.795268  [110000/160000]
loss: 1.916563  [120000/160000]
loss: 1.739235  [130000/160000]
loss: 1.838737  [140000/160000]
loss: 1.829700  [150000/160000]
Test Error: 
 Accuracy: 34.8%, Avg loss: 0.017919 

Epoch 29
-------------------------------
loss: 1.819400  [    0/160000]
loss: 1.953792  [10000/160000]
loss: 1.703164  [20000/160000]
loss: 1.712713  [30000/160000]
loss: 1.873469  [40000/160000]
loss: 1.737391  [50000/160000]
loss: 1.755782  [60000/160000]
loss: 1.889046  [70000/160000]
loss: 1.716759  [80000/160000]
loss: 1.948102  [90000/160000]
loss: 1.807400  [100000/160000]
loss: 1.793884  [110000/160000]
loss: 1.914460  [120000/160000]
loss: 1.734820  [130000/160000]
loss: 1.838700  [140000/160000]
loss: 1.828575  [150000/160000]
Test Error: 
 Accuracy: 34.9%, Avg loss: 0.017907 

Epoch 30
-------------------------------
loss: 1.820360  [    0/160000]
loss: 1.950700  [10000/160000]
loss: 1.702545  [20000/160000]
loss: 1.711027  [30000/1600

loss: 1.750081  [60000/160000]
loss: 1.879449  [70000/160000]
loss: 1.719469  [80000/160000]
loss: 1.938959  [90000/160000]
loss: 1.785555  [100000/160000]
loss: 1.780136  [110000/160000]
loss: 1.898960  [120000/160000]
loss: 1.707216  [130000/160000]
loss: 1.838159  [140000/160000]
loss: 1.813495  [150000/160000]
Test Error: 
 Accuracy: 35.1%, Avg loss: 0.017805 

Epoch 43
-------------------------------
loss: 1.825559  [    0/160000]
loss: 1.924942  [10000/160000]
loss: 1.699211  [20000/160000]
loss: 1.697813  [30000/160000]
loss: 1.873858  [40000/160000]
loss: 1.732333  [50000/160000]
loss: 1.750061  [60000/160000]
loss: 1.879036  [70000/160000]
loss: 1.719653  [80000/160000]
loss: 1.938648  [90000/160000]
loss: 1.784239  [100000/160000]
loss: 1.779630  [110000/160000]
loss: 1.897974  [120000/160000]
loss: 1.706138  [130000/160000]
loss: 1.838199  [140000/160000]
loss: 1.812239  [150000/160000]
Test Error: 
 Accuracy: 35.1%, Avg loss: 0.017800 

Epoch 44
----------------------------

In [13]:
y = nn.functional.softmax(model(torch.tensor(final_test.values.astype(np.float32))),dim=1)

In [14]:
print(y.size())

torch.Size([100000, 9])


In [15]:
sub = pd.DataFrame(y.detach().numpy())

In [16]:
lis = [f"Class_{i}" for i in range(1,10)]
sub.columns = lis
sub.head()

Class_1   Class_2   Class_3   Class_4   Class_5   Class_6   Class_7  \
0  0.050426  0.402919  0.148458  0.019904  0.019904  0.071508  0.049783   
1  0.034143  0.011562  0.011562  0.012933  0.011562  0.036009  0.463141   
2  0.029566  0.005584  0.005584  0.008478  0.005584  0.191856  0.414550   
3  0.044152  0.015690  0.015690  0.028519  0.015690  0.015690  0.569710   
4  0.050926  0.008723  0.010947  0.009560  0.008723  0.008723  0.413919   

    Class_8   Class_9  
0  0.076371  0.160727  
1  0.352603  0.066486  
2  0.170723  0.168074  
3  0.123379  0.171478  
4  0.265673  0.222805

In [17]:
subm = pd.concat([iden,sub],axis = 1)
subm.head()

id   Class_1   Class_2   Class_3   Class_4   Class_5   Class_6  \
0  200000  0.050426  0.402919  0.148458  0.019904  0.019904  0.071508   
1  200001  0.034143  0.011562  0.011562  0.012933  0.011562  0.036009   
2  200002  0.029566  0.005584  0.005584  0.008478  0.005584  0.191856   
3  200003  0.044152  0.015690  0.015690  0.028519  0.015690  0.015690   
4  200004  0.050926  0.008723  0.010947  0.009560  0.008723  0.008723   

    Class_7   Class_8   Class_9  
0  0.049783  0.076371  0.160727  
1  0.463141  0.352603  0.066486  
2  0.414550  0.170723  0.168074  
3  0.569710  0.123379  0.171478  
4  0.413919  0.265673  0.222805

In [19]:
for i in range(1,10):
    subm[f"Class_{i}"] = subm[f"Class_{i}"].round(decimals = 4)
subm.head()

id  Class_1  Class_2  Class_3  Class_4  Class_5  Class_6  Class_7  \
0  200000   0.0504   0.4029   0.1485   0.0199   0.0199   0.0715   0.0498   
1  200001   0.0341   0.0116   0.0116   0.0129   0.0116   0.0360   0.4631   
2  200002   0.0296   0.0056   0.0056   0.0085   0.0056   0.1919   0.4145   
3  200003   0.0442   0.0157   0.0157   0.0285   0.0157   0.0157   0.5697   
4  200004   0.0509   0.0087   0.0109   0.0096   0.0087   0.0087   0.4139   

   Class_8  Class_9  
0   0.0764   0.1607  
1   0.3526   0.0665  
2   0.1707   0.1681  
3   0.1234   0.1715  
4   0.2657   0.2228

In [20]:
subm.to_csv('submissionfinal.csv',index = False,header = True)